var __isNavigating=!1,componentCache=[];window.$insecureEval=eval;window.Planifolia={};window.PlanifoliaSettings={onNavigating:()=>{},onNavigated:()=>{},onFetch:()=>{},handleFileResolve:f=>f,basePath:"/view/",delayNavigation:0,container:null,autoRewriteLinks:!0}
window.Planifolia.contentTo=(target,path)=>{window.PlanifoliaSettings.onNavigating();window.PlanifoliaSettings.onFetch(path);__isNavigating=!0;var routerFile=window.Planifolia.resolveFile(path);fetch(routerFile).then(res=>res.text()).then(text=>{target.innerHTML=text,window.Planifolia.fetchComponents(target),window.Planifolia.fetchElements(target)})}
window.Planifolia.fetchTo=(target,path)=>{window.PlanifoliaSettings.onNavigating();window.PlanifoliaSettings.onFetch(path);__isNavigating=!0;var routerFile=window.Planifolia.resolveFile(path);fetch(routerFile).then(res=>res.text()).then(text=>{let newElement=Planifolia.replaceElementBy(target,text);window.Planifolia.fetchComponents(newElement);window.Planifolia.fetchElements(newElement)})}
window.Planifolia.initializeAutoRouter=()=>{window.addEventListener("hashchange",function(){window.Planifolia.routerFetchPage()}),window.Planifolia.routerFetchPage()}
window.Planifolia.routerFetchPage=()=>{if(window.PlanifoliaSettings.container==null)throw"Please, define the window.PlanifoliaSettings.container before running the router!";var path=window.location.hash.replace("#/","");if(window.path="/"+path.replace(/^\//,""),window.pathAndQuery=window.path,path==""&&(path="index",window.location.href="#/"),path.includes("?")){let querystring=path.substring(path.indexOf("?"));window.query=window.Planifolia.parseQuery(querystring);path=path.substring(0,path.indexOf("?"));window.path=window.path.substring(0,window.path.indexOf("?"));path==""&&(path="index")}else window.query={};var routerFile=window.Planifolia.resolveFile(path);window.locationFile=routerFile;window.PlanifoliaSettings.onNavigating();__isNavigating=!0;let delay=window.PlanifoliaSettings.delayNavigation;setTimeout(()=>{fetch(routerFile).then(res=>res.text()).then(text=>{window.PlanifoliaSettings.container.innerHTML=text,window.Planifolia.fetchComponents(window.PlanifoliaSettings.container),window.Planifolia.fetchElements(window.PlanifoliaSettings.container)})},delay)}
window.Planifolia.fetchComponents=target=>{var exts=target.querySelectorAll("include");if(exts.length==0){window.PlanifoliaSettings.onNavigated();__isNavigating=!1;return}exts.forEach(async e=>{let name=e.getAttribute("name"),componentUrl=window.Planifolia.resolveFile(name),text="";componentCache[componentUrl]==undefined?(text=await fetch(componentUrl).then(res=>{if(res.ok)return res.text();throw new Error(`Cannot fetch include ${name}.`);}),componentCache[componentUrl]=text):text=componentCache[componentUrl];for(const attr of e.attributes){let attrName=attr.name,attrValue=attr.value;if(attrName.startsWith("@"))attrName=attrName.substr(1);else continue;const attrRgx=new RegExp("(?<!@)@"+attrName+"\\b","gi");text=text.replace(attrRgx,attrValue)}let newElement=document.createElement(null);newElement.innerHTML=text;newElement=newElement.firstChild;e.replaceWith(newElement);window.Planifolia.fetchElements(newElement);window.Planifolia.fetchComponents(newElement)})}
window.Planifolia.fetchElements=target=>{target.querySelectorAll("script").forEach(s=>{s.remove();try{window.$insecureEval(s.innerText)}catch(e){throw e;}}),window.PlanifoliaSettings.autoRewriteLinks&&target.querySelectorAll("a").forEach(e=>{let href=e.getAttribute("href");href!=null&&href.startsWith("/")&&!href.startsWith("#/")&&e.setAttribute("href","#"+href)})}
window.Planifolia.joinPaths=(...args)=>{var output="";for(const path of args)output+=path.replace(/^\/|\/$/g,"")+"/";return output.substring(0,output.length-1)}
window.Planifolia.parseQuery=queryString=>{for(var query={},pairs=(queryString[0]==="?"?queryString.substr(1):queryString).split("&"),i=0;i<pairs.length;i++){var pair=pairs[i].split("=");query[decodeURIComponent(pair[0])]=decodeURIComponent(pair[1]||"")}return query}
window.Planifolia.replaceElementBy=(element,text)=>{let newElement=document.createElement(null);return newElement.innerHTML=text,newElement=newElement.firstChild,element.replaceWith(newElement),element}
window.Planifolia.resolveFile=partialName=>{var basePath=window.PlanifoliaSettings.basePath,prefix=window.location.origin+window.location.pathname,result=window.Planifolia.joinPaths(prefix,basePath,partialName+".html");return window.PlanifoliaSettings.handleFileResolve(result)}
